[package]
name = "vectorium"
version = "0.1.0"
edition = "2024"

[dependencies]
vectorium-db = { path = "./vectorium-db" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
env_logger = "0.11.8"
dotenvy = "0.15"
log = "0.4"
