[package]
name = "vectorium-db"
version = "0.1.0"
edition = "2024"

[dependencies]
qdrant-client = "1.9.0"
fastembed = "5.1.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
glob = "0.3.1"
thiserror = "2.0.16"
log = "0.4"
md5 = "0.8.0"
