[package]
name = "vectorium-api"
version = "0.1.0"
edition = "2024"

[dependencies]
qdrant-client = "1.15.0"
tokio = { version = "1.0", features = ["full"] }
axum = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vectorium-common = { path = "../vectorium-common" }
