[package]
name = "vectorium-common"
version = "0.1.0"
edition = "2024"

[dependencies]
qdrant-client = "1.15.0"
tokio = { version = "1.47.1", features = ["full"] }
rust-bert = "0.23.0"
console = { version = "0.16", features = ["std"] }
